server.port=9090

spring.application.name=GATEWAY-SERVICE
spring.cloud.discovery.enabled=true
eureka.instance.prefer-ip-address=true

spring.main.web-application-type=reactive
spring.main.allow-bean-definition-overriding=true
